services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - redditClone:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
volumes:
  redditClone:
