import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import AuthProvider from "./context/AuthProvider";
import { Toaster } from "@/components/ui/toaster";
import Provider from "@/providers/Provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="w-full h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full h-full`}
      >
        <Provider>
          <AuthProvider>

            <Navbar />


            <div className="px-16 ml-auto mr-auto w-full flex max-w-7xl pt-20 h-full">
              {children}

            </div>
            <Toaster />
          </AuthProvider>
        </Provider>

      </body>
    </html>
  );
}
